# Generated by Django 5.2.3 on 2025-06-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='source_panchayat',
            new_name='Destination',
        ),
    ]
